admin_password = "Mikecandys0cxdInBody0.1#"
database_url = "postgresql+psycopg2://postgres.prgrwqzpswvvtzfnelsu:Mikecandys0cxd0.1@aws-0-us-west-2.pooler.supabase.com:5432/postgres"

# -- DataBase: Mikecandys0cxd0.1 --